game = {

    '奥特曼': 'atm',
    '被尘封的故事' : 'bcfdgs',
    '超进化物语':'cjhwy',
    '传奇召唤师':'cqzhs',
    '重生西游':'csxy',
    '斗罗大陆3':'dldl3',
    '胡莱三国2':'hlsg2',
    '葫芦娃': 'hlw',
    '葫芦兄弟':'hlxd',
    '海贼新世界':'hzxsj',
    '军舰帝国':'jjdg',
    '六道忍者':'ldrz',
    '雷鸣三国':'lmsg',
    '萌兵战将':'mbzj',
    '莽荒纪':'mhj',
    '魔兽三国':'mssg',
    '全民挂三国':'qmgsg',
    '神道H5':'sd',
    '三国萌妖传':'sgmyz',
    '三国之旅':'sgzl',
    '时空之旅':'skzl',
    '少年封神':'snfs',
    '天朝小将':'tcxj',
    '天书奇谈':'tsqt',
    '推搡三国':'tssg',
    '我有上将':'wysj',
    '新街机捕鱼':'xjjby',
    '西游奇遇记':'xyqyj',
    '勇敢者西游':'ygzxy',
    '游戏王':'yxw',
    '中超荣耀':'zcry',
    '最强王者':'zqwz',
    '砖石精灵':'zsjl',
    '航海王燃烧意志':'hhw',
}

channel_name = {
    '小y':'xiaoy',
    '小沃':'xiaowo',
    '测试':'test',
    '阿里TV':'alitv',
    '大麦':'damai',
    '海信TV':'haixin',
    '康佳':'kangjia',
    '酷开':'kukai',
    'TCL':'tcl',
    '王素':'wangsu',
    '小米':'xiaomi',
    '乐融':'lerong',
    '华为TV':'huaweitv',
    '百事通PAY':'baishitongpay',
    '百事通':'baishitong',
    '小七':'xiaoqi',
    '乐嗨嗨':'lehaihai',
    '熊猫玩':'xiongmaowan',
    '游戏范':'youxifan',
    '九妖':'jiuyao',
    '联想':'lianxiang',
    '长虹':'changhong',
    '创维':'chuangwei',
    '易视腾':'yishiteng',
    '游豪':'youhao',
    '爱奇艺':'aiqiyi',
    '暴风TV':'baofengtv',
    '大麦_xiaoy':'damai_xiaoy',
    '飞利浦':'feilipu',
    '飞利浦智象':'feilipu_zhixiang',
    '海尔':'haier',
    '视博云':'shiboyun',
    '视博云_xiaoy':'shiboyun_xiaoy',
    '未来电视':'weilaids',
    '熊猫':'xiongmao',
    '讯码':'xunma',


}